server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:YRXING/springcloud-config.git #github上面的git仓库名
          #uri: https://github.com/YRXING/springcloud-config.git
          #搜索目录
          search-paths:
            - springcloud-config
#          username:
#          password:

      #读取分支
      label: main

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
