server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route             #路由ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**      #断言，路径相匹配的进行路由

        - id: payment_route2             #路由ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**      #断言，路径相匹配的进行路由
            - After=2021-03-19T17:04:06.087+08:00[Asia/Shanghai] #表示在这个时间之后，请求路由才有效
            #- before=2021-03-19T17:04:06.087+08:00[Asia/Shanghai]
            #- between=2021-03-19T17:04:06.087+08:00[Asia/Shanghai]
            #Cookie Route Predicate需要两个参数，一个是Cookie name，一个是正则表达式。路由规则会通过获取对应的Cookie name值和正则表达式去匹配，如果匹配上就会执行路由，如果没有则不执行。
            - Cookie=username,zzyy

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #微服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
